export const BuyerActionTypes = {
    FETCH_CURRENT_BUYER_PROFILE_START: 'FETCH_CURRENT_BUYER_PROFILE_START',
    FETCH_CURRENT_BUYER_PROFILE_SUCCESS: 'FETCH_CURRENT_BUYER_PROFILE_SUCCESS',
    FETCH_CURRENT_BUYER_PROFILE_FAILURE: 'FETCH_CURRENT_BUYER_PROFILE_FAILURE',

    FETCH_USER_BUYER_PROFILE_START: 'FETCH_USER_BUYER_PROFILE_START',
    FETCH_USER_BUYER_PROFILE_SUCCESS: 'FETCH_USER_BUYER_PROFILE_SUCCESS',
    FETCH_USER_BUYER_PROFILE_FAILURE: 'FETCH_USER_BUYER_PROFILE_FAILURE',

    UPDATE_USER_BUYER_PROFILE_START: 'UPDATE_USER_BUYER_PROFILE_START',
    UPDATE_USER_BUYER_PROFILE_SUCCESS: 'UPDATE_USER_BUYER_PROFILE_SUCCESS',
    UPDATE_USER_BUYER_PROFILE_FAILURE: 'UPDATE_USER_BUYER_PROFILE_FAILURE',

    UPDATE_CURRENT_BUYER_PROFILE_START: 'UPDATE_CURRENT_BUYER_PROFILE_START',
    UPDATE_CURRENT_BUYER_PROFILE_SUCCESS: 'UPDATE_CURRENT_BUYER_PROFILE_SUCCESS',
    UPDATE_CURRENT_BUYER_PROFILE_FAILURE: 'UPDATE_CURRENT_BUYER_PROFILE_FAILURE',
}