export const RoutingActionTypes = {
    SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',
    SET_LAST_ATTEMPTED_ROUTE: 'SET_LAST_ATTEMPTED_ROUTE',
    SET_RESUME_SAVED_ROUTE: 'SET_RESUME_SAVED_ROUTE',
    SET_ROUTE_MOUNT_STATUS: 'SET_ROUTE_MOUNT_STATUS',
}